driver:
  name: vagrant
  forward_agent: true
  customize:
    cpus: 8
    memory: 8192
  synced_folders: [['.', '/home/vagrant/chef-fips']]

provisioner:
  require_chef_omnibus: 12.5.1

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: centos-7.2
    run_list: omnibus-delivery::epel
  - name: centos-6.7
    run_list: omnibus-delivery::epel

attribute_defaults: &attribute_defaults
  build_user:          vagrant
  build_user_group:    vagrant
  build_user_password: vagrant

suites:
  - name: default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir: /opt/chef-fips
    run_list:
      - omnibus::default
  - name: test
    driver:
      network:
        - ["private_network", {ip: "192.168.44.89"}]
